import { useGLTF } from "@react-three/drei";

export function BeachHouse(props) {
    const { nodes, materials } = useGLTF("/beachhouse.glb");
    return (
        <group {...props} dispose={null} scale={0.2}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh rotation={[-Math.PI/2, 0, 0]} scale={40} position={[0,-7.5,0]}>
                    <planeGeometry args={[1,1,16,16]} />
                    <meshLambertMaterial color={'salmon'}/>
                </mesh>
                <mesh
                geometry={nodes.pCube1_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube2_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube5_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube6_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube7_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube8_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube9_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder1_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder2_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder3_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube10_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube12_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube13_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube14_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube15_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube16_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube17_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube18_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube19_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube20_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube21_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder29_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube22_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube25_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder30_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube26_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder31_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube27_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube28_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder32_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube29_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube30_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube31_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube32_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube33_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface1_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder37_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface5_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface7_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube41_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube42_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube43_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube44_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube45_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube46_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube47_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube48_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube49_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube50_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pSphere3_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pSphere4_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pSphere5_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pSphere6_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pSphere7_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                {/* <mesh
                geometry={nodes.pCylinder38_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                /> */}
                <group
                position={[9.88, -0.62, -0.57]}
                rotation={[-Math.PI, 1.47, -Math.PI]}
                >
                <mesh
                    geometry={nodes.polySurface23_Cabin_MAT_0.geometry}
                    material={materials.Cabin_MAT}
                />
                <mesh
                    geometry={nodes.polySurface24_Cabin_MAT_0.geometry}
                    material={materials.Cabin_MAT}
                />
                <mesh
                    geometry={nodes.polySurface25_Cabin_MAT_0.geometry}
                    material={materials.Cabin_MAT}
                />
                </group>
                <mesh
                geometry={nodes.pCube56_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube57_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube58_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube59_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube60_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube61_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube62_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder42_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder43_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder44_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCylinder50_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface26_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface27_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface28_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.polySurface17_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube63_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                <mesh
                geometry={nodes.pCube64_Cabin_MAT_0.geometry}
                material={materials.Cabin_MAT}
                />
                {/* <mesh
                geometry={nodes.pSphere12_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere13_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere14_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere15_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere16_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere17_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere18_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere19_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere20_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere21_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere22_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere23_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere24_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere25_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere26_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere27_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere28_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere29_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere30_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                />
                <mesh
                geometry={nodes.pSphere31_Water_MAT_0.geometry}
                material={materials.Water_MAT}
                /> */}
            </group>
            </group>
        </group>
    );
}
useGLTF.preload("/beachhouse.glb");


function Models(){
    return(
        <>
            <BeachHouse />
        </>
    )
}
export default Models
